### ISSUE TITLE
Encoding problem in WiC64 emulation

### ISSUE THREAD

**Issue by EgonOlsen71** [abbruzze/kernal64#16]
Hi,

there seems to be a problem in the WiC64 emulation. When I call an URL like:

`http://62.227.184.12:8192/WebCompiler/Download?size=2048&part=1&file=7f683251-7f9b-4453-92d8-02611d045f24%2F3202642-44-test.bin`

it seems to be doing an additional encoding of the %, which results in this URL to be actually called:

`http://62.227.184.12:8192/WebCompiler/Download?size=2048&part=1&file=7f683251-7f9b-4453-92d8-02611d045f24%252F3202642-44-test.bin`

Looks like as if it has encoded the % to %25, which it shouldn't do. On the server, the decoded Parameter is then

`7f683251-7f9b-4453-92d8-02611d045f24%2F3202642-44-test.bin`

when it should actually be 

`7f683251-7f9b-4453-92d8-02611d045f24/3202642-44-test.bin`

This works fine on the original hardware.

**Comment by abbruzze** [comment]
Hello and thanks for this notification.
At the beginning I thought that the WiC64 was in charge for url encoding.
When I got a look to the firmware source I discovered that the url encoding must be done by the client (C64), because I didn't find any url encoding there.
So, wrongly I forgot to remove it.
I'm going to commit the fix and uploading the new zip file: use the same location to download, it will not change.
Check the Kerna64's new version: must be 1.7.3b5.
After downloading, you could replace just the library: kernal64.jar into lib directory.
