### ISSUE TITLE
up/down & left/right

### ISSUE THREAD

**Issue by CouragePTV** [abbruzze/kernal64#17]
No bug, but I would like to be able to assign the arrow keys individually and not exclusively in combination with Shift+down/Shift+right.

A great emulator that has helped me the of WIC64 support countless times! <3

**Comment by abbruzze** [comment]
The current keyboard emulation cannot fullfil your requirement because on the real thing you have to push both SHIFT and CRSR-UP or DOWN.
I would need to introduce another implementation where you would map any host key with any combination of C64 keys. I will take this in mind for the next features.

I’m very happy to helped you with WiC64.
