### ISSUE TITLE
Geos: mouse pointer moves extremely quickly

### ISSUE THREAD

**Issue by sdrinf** [abbruzze/kernal64#5]
Repro steps:
* download geos (eg https://www.lyonlabs.org/commodore/onrequest/geos/ )
* boot it up
* enable mouse capture
* move mouse

Expected result: mouse moves at humanly speed
Observed result: cursor moves extremely quickly

Suggestion: having eg a pointer speed slider would allow me to configure this proportionally to current window side

Thanks!

**Comment by abbruzze** [comment]
Hello Dragon and thanks for your interest in Kernal64.
This issue has been fixed (or partially fixed) in the incoming 1.6.0 release I have been working on since December.

Below I've attached kernal64.zip file that must be renamed in kernal64.jar. Put it in the lib directory of your installation to switch to 1.6.0 version.

Thanks.

[kernal64.zip](https://github.com/abbruzze/kernal64/files/4308199/kernal64.zip)
