### ISSUE TITLE
RR-net support

### ISSUE THREAD

**Issue by sdrinf** [abbruzze/kernal64#6]
Feature request: RR-net seems the current de-facto standard for networking (and has widest software support).  Can we have this implemented in kernal64?
Thanks for the hard work!

**Comment by abbruzze** [comment]
Hello again Dragon.
The RR-net card is extremely difficult to emulate since it implements a complete tcp/ip stack.
I thought a lot of times to reproduce it but every time I started to study the data sheet of its internal chip I gave up: too time consuming.

At the moment it's not on my to-do list, mainly because I'm the only member of my team ;-)
Anyway Kernal64 provides internet access via userport or SwiftLink card using a sort of Wi-Fi internal card, useful to connect mainly to the bbs.
